version: "3"
services:
  app:
    image: node:14
    working_dir: /work
    volumes: [ "./:/work" ]
    command: [ sh, -c, "yarn build && yarn start-server" ]
    ports: [ "7780:8080" ]
    environment:
      - "PORT=8080"
  cypress:
    image: cypress/browsers:node14.7.0-chrome84
    depends_on: [ app ]
    working_dir: /work
    volumes: [ ".:/work" ]
    environment:
      - "CYPRESS_baseUrl=http://app:8080"
    command:
      - sh
      - -c
      - |
        yarn wait-on tcp:app:8080 &&
        echo "
        Skipping Cypress. To execute Cypress tests, run:
        docker-compose run script yarn cypress install &&
        docker-compose run cypress yarn cypress run"
  script:
    image: node:14
    working_dir: /work
    stop_signal: SIGKILL
    volumes: [ ".:/work" ]
    command:
      - bash
      - -c
      - |
        yarn wait-on tcp:app:8080 &&
        echo "
        To execute a script, run:
        docker-compose run script {command}"
